version: 0.0
os: linux

file_exists_behavior: OVERWRITE

files:
  - source: /
    destination: /home/ubuntu/cicdproject/springbootapp
    overwrite: yes
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu
